### ISSUE TITLE
运行后端main.go时报错

### ISSUE THREAD

**Issue by Bald-mans** [tiger1103/gfast#62]
build running pid: 19028
panic: possible config files "config" or "config.toml/yaml/yml/json/ini/xml/properties" not found in resource manager or following system searching paths:
1. F:\GO-project\src\gfast\
2. F:\GO-project\src\gfast\config/
3. F:\GO-project\src\gfast\manifest/config

goroutine 1 [running]:
github.com/gogf/gf/v2/os/gcfg.(*Config).MustGet(0x0?, {0x16d14c0?, 0xc0003d7170?}, {0xfa8745?, 0x604294?}, {0x0?, 0x50?, 0xc0002aba90?})
        C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.3.1/os/gcfg/gcfg.go:167 +0x5e
github.com/tiger1103/gfast/v3/internal/app/common/logic/cache.New()
        F:/GO-project/src/gfast/internal/app/common/logic/cache/cache.go:27 +0x69
github.com/tiger1103/gfast/v3/internal/app/common/logic/cache.init.0()
        F:/GO-project/src/gfast/internal/app/common/logic/cache/cache.go:19 +0x17

**Comment by tiger1103** [comment]
项目数据库文件 resource/data/gfast-v32.sql 创建数据库导入后修改配置`manifest/config/config.yaml.bak` 复制改为`manifest/config/config.yaml`
